### ISSUE TITLE
creating the application?

### ISSUE THREAD

**Issue by amcsSH** [bertrik/luftdatenmapper#1]
Hi bertrik,

a happy new year and a very nice project. 
How can I create the application after cloning it?

Thanks in advance
Andreas

**Comment by bertrik** [comment]
Go to directory workspace/gradle, then run the gradlew executable with argument distTar or distZip, for example:
cd luftdatenmapper/workspace/gradle
./gradlew distTar
cp ../luftdatenmapper/build/distributions/luftdatenmapper.tar ~

This compiles the application and packages it into a .tar archive and copies it to your home directory.
You can untar the tar file and run it with the bin/luftdatenmapper.sh script (Linux) or bin/luftdatenmapper.bat script (Windows).

Gradle is a kind of build system, it downloads dependencies (like libraries) and builds it into an application archive with a nice startup script. You need to have the Java JDK 8 installed and available on the path.

The application is very much a work in progress.
The luftdatenmapper.properties file contains the settings you can configure, I hope it is self-explanatory. If this file is absent, a new file is created with default settings.
The renderjobs.json file defines what images are generated.
The luftdatenmapper.log file is the Java log4j log file.

**Comment by amcsSH** [comment]
Thanks a lot.

Please change in the file: luftdatenmapper.properties
the config variable: _cmd.convert_ to _cmd.animate_

**Comment by bertrik** [comment]
I made some last minute changes recently to update the automatic animation process (it was taking up a lot of CPU power) and did some manual work to animate the particulate matter peak from the new year's celebrations. So indeed this file was not completely up-to-date.

**Comment by amcsSH** [comment]
Great, thank you, it's working.

How do you select the Netherland sensors only from LuftDataInfo API?   I would like to select the sensors of an area in Germany (in the first step).

**Comment by bertrik** [comment]
I simply use all sensors, the algorithm weighs them by distance *squared* so far away sensors get a very small weight. If you look closely at the actual JSON data, I think there is also a country field, you could filter programmatically on that perhaps.

According to the API description, you can also specify the country as part of the luftdaten request URL, for example:
http://api.luftdaten.info/v1/filter/country=BE
(see https://github.com/opendata-stuttgart/meta/wiki/APIs)

**Comment by bertrik** [comment]
I changed the properties a bit (this will keep happening from time to time): now only sensors are considered from an area 3x3 times the size of the area being shown. Also I added a distance limit: if no sensors are near, a special colour (transparent grey) is used to indicate that no interpolated value has been calculated. I removed the animation option.
